import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Link from "next/link";
import {cookies} from "next/headers";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className={"navbar bg-primary"}>
					<div className={"max-w-4xl w-full mx-auto flex justify-between px-2 py-4"}>
						<h1>Fireship 🔥 Next.js Course </h1>
						<nav>
							<ul className={"flex gap-x-2"}>
								{cookies().get("next-auth.session-token") ? (
									<li className={"link"}>
										<Link href={"api/auth/signout"}>Sign Out</Link>
									</li>
								) : (
									<li className={"link"}>
										<Link href={"/api/auth/signin"}>Sign in</Link>
									</li>
								)}
								<li className={"link"}>
									<Link href={"#"}>About</Link>
								</li>
								<li className={"link"}>
									<Link href={"#"}>Contacts</Link>
								</li>
							</ul>
						</nav>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
// todo make a component WithAuth that wraps the layout and if not connected (no token) then it displays the login page
